# Generated by Django 2.2.6 on 2019-10-10 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='ausführen',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 14, 11, 25, 132102)),
        ),
    ]
