# Generated by Django 2.2.6 on 2019-10-10 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20191010_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='ausführen',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 14, 14, 51, 632621)),
        ),
    ]
