# Generated by Django 2.2.6 on 2019-10-13 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20191010_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='ausführen',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 13, 15, 14, 59, 609870)),
        ),
    ]
